config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "gifs#index"
  resources :users, only: [:new, :create, :show]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :gif_categories
  has_many :gifs, through: :gif_categories

end

app/models/favorite_gif.rb
class FavoriteGif < ApplicationRecord

  belongs_to :user
  belongs_to :gif

end

app/models/gif.rb
class Gif < ApplicationRecord

 has_many :gif_categories
 has_many :categories, through: :gif_categories
 has_many :favorite_gifs
 has_many :users, through: :favorite_gifs

end

app/models/gif_category.rb
class GifCategory < ApplicationRecord

  belongs_to :gif
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :favorite_gifs
  has_many :gifs, through: :favorite_gifs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      User.new(first_name: "Guest")
    end
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
    @gifs = Gif.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Login successful. Welcome back #{current_user.first_name}"
      redirect_to user_path(user)
    else
      flash.now[:invalid] =  "invalid credentials, please try again"
      redirect_to login_path
    end
  end

  def destroy
    fail
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:welcome_new_user] = "Welcome to GifyApp, #{@user.first_name}"
      redirect_to user_path(@user)
    else
      flash[:invalid_submission] = "Invalid submission, please try again"
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gifs/index.html.erb
<h1>All Gifs</h1>

  <% @gifs.each do |gif| %>
  <div class="gifs list">
    <img src="<%= gif.image_path %>" alt="gif_image" />
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GifGenerator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- create "if" block for "if user logged in, yield this"
    else, "yield this other thing", place all in shared folder -->
    <nav class="auth">
      <% if current_user.id %>
        <%= render partial: "shared/logged_in_nav" %>
      <% else %>
        <%= render partial: "shared/not_logged_in_nav" %>
      <% end %>
    </nav>

    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "flash_#{type}" %>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/shared/_logged_in_nav.html.erb
<%= link_to "Logout", logout_path %>

app/views/shared/_not_logged_in_nav.html.erb
<%= link_to "Create New Account", new_user_path %>
<%= link_to "Log In", login_path %>

app/views/users/new.html.erb
<h3>Please create a new account:</h3>
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br />
  <%= f.label :email_address %>
  <%= f.text_field :email %><br />
  <%= f.label :password %>
  <%= f.password_field :password %><br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br />

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h3>Welcome, <%= @user.first_name %></h3>